{% set name = "kartothek" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c352e9884fbbdbedab359987f9c854e885aa99f1d8bb5dee53a69dc9e8996953

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - setuptools_scm
    - python >=3.6
  run:
    - dask
    - decorator
    - msgpack-python >=0.5.2
    - numpy !=1.15.0,!=1.16.0
    - pandas >=0.23.0,!=1.0.0
    - pyarrow >=0.17.1,!=1.0.0,<4
    - python >=3.6
    - simplejson
    - simplekv
    - storefact
    - toolz
    - typing_extensions
    - urlquote >=1.1.3
    - zstandard
    - attrs
    - click
    - prompt-toolkit
    - pyyaml

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kartothek
    - kartothek.core
    - kartothek.io
    - kartothek.io.dask
    - kartothek.serialization
    - kartothek.core.urlencode
    - kartothek.api
    - kartothek.api.consistency
    - kartothek.api.discover
    - kartothek.cli
    - kartothek.utils

about:
  home: https://github.com/JDASoftwareGroup/kartothek
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A consistent table management library in python
  doc_url: https://kartothek.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - fjetter
    - xhochy
