{% set name = "kartothek" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13b12562ea9d3aba97dfe8edf3e306e58d00101a6d9c79b1845b1d89d9a3799b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools_scm
    - python >=3.6
  run:
    - dask !=2021.5.1,!=2021.6.0
    - decorator
    - msgpack-python >=0.5.2
    - numpy !=1.15.0,!=1.16.0
    - pandas >=0.23.0,!=1.0.0
    - pyarrow >=0.17.1,!=1.0.0,<7
    - python >=3.6
    - simplejson
    - simplekv
    - storefact
    - toolz
    - typing_extensions
    - urlquote >=1.1.3
    - zstandard
    - attrs
    - click
    - prompt-toolkit
    - pyyaml
    - deprecation

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kartothek
    - kartothek.core
    - kartothek.io
    - kartothek.io.dask
    - kartothek.serialization
    - kartothek.core.urlencode
    - kartothek.api
    - kartothek.api.consistency
    - kartothek.api.discover
    - kartothek.cli
    - kartothek.utils

about:
  home: https://github.com/JDASoftwareGroup/kartothek
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A consistent table management library in python
  doc_url: https://kartothek.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - fjetter
    - xhochy
