{% set name = "kartothek" %}
{% set version = "3.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4fc8c49116a1d9e17091878d1383869ea40290b03dff191db6f6c70649ef525

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - setuptools_scm
    - python >=3.6
  run:
    - dask
    - decorator
    - funcsigs
    - msgpack-python >=0.5.2
    - numpy !=1.15.0,!=1.16.0
    - pandas >=0.23.0
    - pyarrow >=0.11.1, !=0.14.0
    - python >=3.6
    - simplejson
    - storefact
    - urlquote >=1.1.3
    - zstandard

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kartothek
    - kartothek.core
    - kartothek.io
    - kartothek.io.dask
    - kartothek.serialization
    - kartothek.core.urlencode

about:
  home: https://github.com/JDASoftwareGroup/kartothek
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A consistent table management library in python
  doc_url: https://kartothek.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - fjetter
    - xhochy
