travis:
  secure:
    BINSTAR_TOKEN: sAkWcEuqFjYKw0cFcbwk+n0ajsQrUK4ozChNqYioIfO+6GJroz8vSeGA3/GJzOjA+UmP2W6db6olTX6ZZaNpkvL3jAZAnMqO+VmP/Vd9viMn5gfLIxdElWGpLRotP6zEeK3HdItPOs7swrswlvx6Jl6iXHSflSUwPMssToBytvEx+wGnM9O6XwI58o3ahV52V+PNmZGiaC+wJ9YqBF+OLmNbIDxvZ6HfQS2/6CHBdkHcPA+F2zs1EIYDm7UUxv5x/20vlFEVD6LjNBY5uTlajgZ6gLsQoV0jmHFZ2cnL2z6i1cdnotls+xedpGEy8xREMQQWNrYf+FSEJii0S8nA59z6QEXOtkSjNU4qiqt+aEUkwm0S2S4TV6Hl9wVzmWyOuyr+U3CaCpQVh+IP/mv1WuhLaNnxoupzD0UJ5vYjpp59g8B5yMha3Y4/UKYBGmiPdxllNgHEETeFM4PcI8dSHCyTQjWKvgimF3tqghSKCxMzXfrYd5WB2wHhyYKuP0n/rSPlGbD3L0nnuNptR97+9KajhWj/u2kUFM9dik2RBz1DkfGGO6ifsuSQK9dVNCUvzsihi6e0hq6LrD32ukrmpEtc01/B0TBDFJXhxr6+UWX+h005zN5FE0yQHNhzjBQa+FMp//aDxODAzsP2++i5AYXUoA1fHOhxN0l2mciTFhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
