travis:
  secure:
    BINSTAR_TOKEN: qz01lQH7WBdgXFTfcVUqYxXyEvkkc3JQ/wYI52R99FSlQKYw0mX5Y+nunbGmbn7pKu3gDAtweo0QmZtlD/lwV3+tCMgDY6t/3MzlvSwceiN0rN/kl+Rry6KKllwk+jUkLgynJ01qEh0BgLyUGlnfVX/snTKr+EfQAP5WztPQyIc9EWAZXz5QXeynkL0YUOl0D6PFGgFNInGrk5X+OuiXbCQYwNnAaf2H3qyKxWBxKrOc4g479SDRSbDpDVNnmbHdQ70zl8s8UzjUqMcjCrJmDiRwGeyC8OtphJzWzpgg6ARjcvUlcDART8ZTWpuMS5x5Z0IWIeDVRMcQLv24EmMb3Mv5XwhoVUaZ5oPrcSuLpKQVeofR36MlvcHNDi9/CKmTEXg6yT9JilKwSL4wh4syA9/vvbLoz8N4RYPFkvurBKmsnpyi9RtzWPDiXrdLri9V6BuGBi++WEfegiZlFnKO9nfS1z6EMLL2q91i1qSXs8dFFfH0H32JtSnnkjeJI+Q6Uwyif2rqXVIFJn5xv/nedC2LhdOvzRcnFjDh4WvYHR1jEvafgnhCqOgJo/Ryd1SzgL7IzoGUE9GloDI2Us6vw+J1Hw56Rj4UzGMQ/rGBICREWEnF+0pfi7R6hJByZ1/XLdNwdlpWM3IcfvdonvwfL/fYHqMmwca9fq4cfuJmQmY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
